-- =============================================================================
-- 03_grants.sql
-- Run as: SECURITYADMIN
-- Grants privileges per role following least-privilege principle.
-- =============================================================================

-- SECURITYADMIN: manages all privilege grants across the account
USE ROLE SECURITYADMIN;

-- -----------------------------------------------------------------------------
-- Warehouse grants
-- -----------------------------------------------------------------------------

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ETL_TRAINER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ETL_ADMIN;
GRANT USAGE ON WAREHOUSE DEPLOY_WH  TO ROLE ETL_DEPLOYER;
GRANT USAGE ON WAREHOUSE DEPLOY_WH  TO ROLE ETL_ADMIN;
GRANT USAGE ON WAREHOUSE TEST_WH    TO ROLE ETL_TEST_RUNNER;
GRANT USAGE ON WAREHOUSE TEST_WH    TO ROLE ETL_ADMIN;

-- -----------------------------------------------------------------------------
-- Transfer database ownership to ETL_ADMIN so it can manage its own objects
-- -----------------------------------------------------------------------------

GRANT OWNERSHIP ON DATABASE UNIFIED_ETL      TO ROLE ETL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE UNIFIED_ETL_TEST TO ROLE ETL_ADMIN COPY CURRENT GRANTS;

-- Transfer schema ownership (needed after database ownership transfer)
USE ROLE ETL_ADMIN;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE UNIFIED_ETL      TO ROLE ETL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE UNIFIED_ETL_TEST TO ROLE ETL_ADMIN COPY CURRENT GRANTS;

-- Back to SECURITYADMIN for remaining grants
USE ROLE SECURITYADMIN;

-- =============================================================================
-- ETL_DEPLOYER grants
-- Can: manage stages, procedures, tasks; write reference tables in PUBLIC
-- =============================================================================

GRANT USAGE ON DATABASE UNIFIED_ETL TO ROLE ETL_DEPLOYER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE UNIFIED_ETL TO ROLE ETL_DEPLOYER;

-- PUBLIC schema: full control for reference data management
GRANT CREATE TABLE     ON SCHEMA UNIFIED_ETL.PUBLIC TO ROLE ETL_DEPLOYER;
GRANT CREATE STAGE     ON SCHEMA UNIFIED_ETL.PUBLIC TO ROLE ETL_DEPLOYER;
GRANT CREATE PROCEDURE ON SCHEMA UNIFIED_ETL.PUBLIC TO ROLE ETL_DEPLOYER;
GRANT CREATE TASK      ON SCHEMA UNIFIED_ETL.PUBLIC TO ROLE ETL_DEPLOYER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA UNIFIED_ETL.PUBLIC TO ROLE ETL_DEPLOYER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.PUBLIC TO ROLE ETL_DEPLOYER;

-- Read access to other schemas (for verification)
GRANT SELECT ON ALL TABLES IN SCHEMA UNIFIED_ETL.RAW       TO ROLE ETL_DEPLOYER;
GRANT SELECT ON ALL TABLES IN SCHEMA UNIFIED_ETL.FEATURES  TO ROLE ETL_DEPLOYER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.RAW      TO ROLE ETL_DEPLOYER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.FEATURES TO ROLE ETL_DEPLOYER;

-- Execute tasks
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ETL_DEPLOYER;

-- =============================================================================
-- ETL_TRAINER grants
-- Can: read raw data, write features/models, create temp tables
-- =============================================================================

GRANT USAGE ON DATABASE UNIFIED_ETL TO ROLE ETL_TRAINER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE UNIFIED_ETL TO ROLE ETL_TRAINER;

-- RAW schema: read-only
GRANT SELECT ON ALL TABLES IN SCHEMA UNIFIED_ETL.RAW    TO ROLE ETL_TRAINER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.RAW TO ROLE ETL_TRAINER;

-- PUBLIC schema: read reference tables
GRANT SELECT ON ALL TABLES IN SCHEMA UNIFIED_ETL.PUBLIC    TO ROLE ETL_TRAINER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.PUBLIC TO ROLE ETL_TRAINER;

-- FEATURES schema: read + write
GRANT CREATE TABLE ON SCHEMA UNIFIED_ETL.FEATURES TO ROLE ETL_TRAINER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA UNIFIED_ETL.FEATURES    TO ROLE ETL_TRAINER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.FEATURES TO ROLE ETL_TRAINER;

-- MODELS schema: read + write
GRANT CREATE TABLE ON SCHEMA UNIFIED_ETL.MODELS TO ROLE ETL_TRAINER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA UNIFIED_ETL.MODELS    TO ROLE ETL_TRAINER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.MODELS TO ROLE ETL_TRAINER;

-- MONITORING schema: write prediction logs
GRANT CREATE TABLE ON SCHEMA UNIFIED_ETL.MONITORING TO ROLE ETL_TRAINER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA UNIFIED_ETL.MONITORING    TO ROLE ETL_TRAINER;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.MONITORING TO ROLE ETL_TRAINER;

-- Temp tables for intermediate training work
GRANT CREATE TEMPORARY TABLE ON SCHEMA UNIFIED_ETL.FEATURES TO ROLE ETL_TRAINER;

-- =============================================================================
-- ETL_TEST_RUNNER grants
-- Can: full access to test database, read-only on production
-- =============================================================================

-- Full control of test database
GRANT ALL PRIVILEGES ON DATABASE UNIFIED_ETL_TEST TO ROLE ETL_TEST_RUNNER;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE UNIFIED_ETL_TEST TO ROLE ETL_TEST_RUNNER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE UNIFIED_ETL_TEST TO ROLE ETL_TEST_RUNNER;
GRANT CREATE SCHEMA ON DATABASE UNIFIED_ETL_TEST TO ROLE ETL_TEST_RUNNER;

-- Read-only on production (for cross-referencing, never writing)
GRANT USAGE ON DATABASE UNIFIED_ETL TO ROLE ETL_TEST_RUNNER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE UNIFIED_ETL TO ROLE ETL_TEST_RUNNER;
GRANT SELECT ON ALL TABLES IN SCHEMA UNIFIED_ETL.PUBLIC   TO ROLE ETL_TEST_RUNNER;
GRANT SELECT ON ALL TABLES IN SCHEMA UNIFIED_ETL.RAW      TO ROLE ETL_TEST_RUNNER;
GRANT SELECT ON ALL TABLES IN SCHEMA UNIFIED_ETL.FEATURES TO ROLE ETL_TEST_RUNNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.PUBLIC   TO ROLE ETL_TEST_RUNNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.RAW      TO ROLE ETL_TEST_RUNNER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UNIFIED_ETL.FEATURES TO ROLE ETL_TEST_RUNNER;

-- =============================================================================
-- Verify
-- =============================================================================

SHOW GRANTS TO ROLE ETL_DEPLOYER;
SHOW GRANTS TO ROLE ETL_TRAINER;
SHOW GRANTS TO ROLE ETL_TEST_RUNNER;
